name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: Platane/snk@v3
        with:
          github_user_name: DevAbhinav-23
          outputs: |
            dist/github-snake-dark.svg?color_snake=violet&color_dots=#8B5CF6,#A78BFA,#C4B5FD,#DDD6FE,#6D28D9

      - uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.SNAKE_PAT }}
